### ISSUE TITLE
ckan-ng-harvester is running side-by-side with existing legacy harvesters

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#216] opened 2019-12-30 16:33 UTC
As a Data.gov operator, I want ckan-ng-harvester running side-by-side with the legacy harvesters so that I can transition to ckan-ng-harvester in an incremental way.

**Comment by kimwdavidson** [comment] 2020-01-27 17:23
Duplicate of #217. Closing

**Closed by kimwdavidson** 2020-01-27 17:23 UTC
