### ISSUE TITLE
Staging environment for new catalog app

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#296] opened 2020-05-04 14:27 UTC
## User Story

As a data.gov developer, I want production-like environment for the new catalog app, so that any issues with the switch over to production are identified as early as possible, before the switch over.

## Acceptance Criteria
- [x] GIVEN I deploy the data.gov platform to staging
  WHEN I visit https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/
  THEN I can access the new catalog app at its staging URL and see the CKAN datasets page

## Details / tasks
_[adborden] this **appears** large, but the effort isn't significant. Most of the work is fielding BSP tickets and updating configuration in Ansible. As written, it will likely sit in In Progress/Blocked for a sprint or two. _

- [x] Bionic "v2" hosts exist in staging
- [x] New RDS database for catalog in BSP (RITM0734013)
- [x] New solr resources (RITM0734014)
- [x] Update the site certificate (RITM0734015)
- [x] New Load Balancer and/or Netscaler configuration in BSP (RITM0734015)
- [x] DNS (catalog-next)
- [x] Redis in BSP (https://github.com/GSA/datagov-deploy/issues/1537)
- [x] Specify necessary security requirements on Redis (https://github.com/GSA/datagov-deploy/issues/1730)
- [x] Run db init commands
- [x] install SSL certificate to netscaler (RITM0759378)

**Comment by kimwdavidson** [comment] 2020-05-06 18:42
Tom and Esteban to meet on this 5/7/20

**Comment by adborden** [comment] 2020-05-06 18:44
@woodt @estebanruseler fyi, this is the ansible role that configures our self-hosted solr. There is a PR to add the ckan 2.8 schema. Let me know if you need additional info on how solr is setup.

https://github.com/GSA/datagov-deploy-solr/pull/16

**Comment by woodt** [comment] 2020-05-07 18:08
@adborden what version of Solr will we be running?

**Comment by adborden** [comment] 2020-05-19 16:35
We're currently running [5.5.5](https://github.com/GSA/datagov-deploy/blob/7c85fe30fff56d43c49211d6ddc58c9dcc7cd232/ansible/group_vars/all/vars.yml#L73) we should stick to that for now.

Ideally it would be a more recent version, whatever CKAN supports.

**Comment by woodt** [comment] 2020-05-20 18:02
Try Postgres 9.6, 200Gb storage

**Comment by adborden** [comment] 2020-05-20 22:44
RITM0734013 created

Title: New staging RDS Postgres database for catalog Data.gov

Please route to BSP.Infrastructure.

Background: Data.gov is doing a major upgrade of CKAN (https://ckan.org/) the software powering catalog.data.gov. The upgrade plan consists of a complete switchover, having the new infrastructure running side-by-side with the existing one until we've validated the changes. Once validated, we'll do a switchover at the load balancer to put the new version of CKAN into service.

The new RDS instances should be based on the existing configuration of the catalog staging database datagovcatalog.cwyyxljkfrkk.us-east-1.rds.amazonaws.com, with two read replicas, same as the existing database. We'll be starting with an empty database, so there is no need to copy the existing data or seed from an existing snapshot.

Deviations from the existing configuration:
- PostgreSQL version 9.6.x
- Storage volume should be 200 Gb
- Empty database, **not** created from snapshot

Environment: staging

Please do not destroy the existing instances. We will be using the new instances to develop and test and will destroy the old ones only after we've validated the changes in production.

Please don't hesitate to reach out with any questions.

**Comment by adborden** [comment] 2020-05-20 22:45
REQ0529770 - Generic Request - New EC2 instances for Solr Data.gov (staging)

Please route to BSP.Infrastructure.

Background: Data.gov is doing a major upgrade of CKAN (https://ckan.org/) the software powering catalog.data.gov. The upgrade plan consists of a complete switchover, having the new infrastructure running side-by-side with the existing one until we've validated the changes. Once validated, we'll do a switchover at the load balancer to put the new version of CKAN into service.

Please create 3 additional Solr instances for testing in staging. I believe there are existing CloudFormation templates. These instances should be identical to the existing ones, one master and two replicas.

Deviations from the existing configuration: N/A

Environment: staging

Please do not destroy the existing instances. We will be using the new instances to develop and test and will destroy the old ones only after we've validated the changes in production.

Please don't hesitate to reach out with any questions.

**Comment by adborden** [comment] 2020-05-20 22:48
RITM0734015 New catalog-next route for Netscaler Data.gov (staging)

Please route to BSP.Infrastructure.

Background: Data.gov is doing a major upgrade of CKAN (https://ckan.org/) the software powering catalog.data.gov. The upgrade plan consists of a complete switchover, having the new infrastructure running side-by-side with the existing one until we've validated the changes. Once validated, we'll do a switchover at the load balancer to put the new version of CKAN into service.

Please add a Netscaler configuration for catalog-next-datagov.dev-ocsit.bsp.gsa.gov routing to these instances. This should be a similar configuration to catalog-datagov.dev-ocsit.bsp.gsa.gov which exists today:
- catalogweb1d.dev-ocsit.bsp.gsa.gov
- catalogweb2d.dev-ocsit.bsp.gsa.gov

Please add a Netscaler configuration for admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov routing to these instances. This should be a similar configuration to admin-catalog-datagov.dev-ocsit.bsp.gsa.gov which exists today:
- catalogwebpub1d.dev-ocsit.bsp.gsa.gov


Deviations from the existing configuration: N/A

Environment: staging

Please do not destroy the existing instances. We will be using the new instances to develop and test and will destroy the old ones only after we've validated the changes in production.

Please don't hesitate to reach out with any questions.

**Comment by adborden** [comment] 2020-05-21 01:09
Submitted a ticket for the internal [GSA site certificate](https://github.com/GSA/datagov-deploy/wiki/TLS-SSL-Certificates) (RITM0734015).

**Comment by mogul** [comment] 2020-05-28 20:09
There's been enough progress on the outstanding requests that we can put this back `In Progress`.

**Comment by mogul** [comment] 2020-05-28 20:18
Next step is more provisioning requests for FCS/BSP.

**Comment by adborden** [comment] 2020-08-04 23:41
Updated inventory lives on [feature/catalog-next-staging](https://github.com/GSA/datagov-deploy/compare/feature/catalog-next-staging).

**Comment by adborden** [comment] 2020-08-06 01:38
Reminder to self:
- [ ] remove public url

**Comment by adborden** [comment] 2020-08-07 21:17
@pjsharpe07 submitted a ticket to install new staging site certificates on BSP (RITM0759378)

**Comment by adborden** [comment] 2020-08-07 22:36
For database init, running these commands from catalogharvester1d. You'll be prompted for the ckan user password on creation and the admin password on connect.
```
createuser -h $DB_HOST -U $DB_ADMIN_USER -S -D -R -P ckan
psql -h $DB_HOST -U $DB_ADMIN_USER -c "GRANT ckan to $DB_USER;"
createdb -h $DB_HOST -U $DB_ADMIN_USER -O ckan ckan -E utf-8
psql -h $DB_HOST -U $DB_ADMIN_USER -d ckan -c 'CREATE EXTENSION postgis;'
sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckan db init -c /etc/ckan/production.ini
sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckanext-report report initdb -c /etc/ckan/production.ini
sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckanext-archiver archiver init -c /etc/ckan/production.ini
```

**Comment by pjsharpe07** [comment] 2020-08-12 15:39
The new site certificates have been installed 🎉

**Comment by adborden** [comment] 2020-08-12 23:36
I'm moving this to "Blocked" on the ckan-multi board since this is ready for deploy, waiting on the devsecops team's normal sprint release process. Should be live by Thu Aug 20th.

**Comment by adborden** [comment] 2020-08-19 19:12
Confirmed this has been deployed.

**Comment by adborden** [comment] 2020-08-24 17:59
@thejuliekramer you'll need to be connected to the [VPN](https://github.com/GSA/datagov-deploy/wiki/GSA-VPN) in order to access staging.

**Comment by thejuliekramer** [comment] 2020-08-26 13:45
In order to access the VPN I need a working GSA user. My GSA user has been deleted according to GSA IT helpdesk. @hkdctol can you please request I be added again?

**Comment by woodt** [comment] 2020-08-26 21:12
(1) I am able to visit the ckan application catalog-next on staging (via chrome under the GSA VPN.)
(2) I was able to create a test account
(3) I was able to login using the test account
(4) [I deleted the test account.]

This looks good to me.  Ship it!

**Closed** 2020-08-31 15:48 UTC
