### ISSUE TITLE
Harvest object HTML view returns 500

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#531] opened 2020-12-08 16:36 UTC
## How to reproduce

1. https://catalog-next.data.gov/dataset/low-altitude-aerial-imagery-obtained-with-unmanned-aerial-systems-uas-flights-over-black-beach
1. Under "Metadata Source", click "View Full Metadata"

## Expected behavior

The HTML view of the source metadata is rendered.

See [catalog-classic](https://catalog.data.gov/dataset/low-altitude-aerial-imagery-obtained-with-unmanned-aerial-systems-uas-flights-over-black-beach-) for similar behavior.

## Actual behavior

500, server error.

**Comment by thejuliekramer** [comment] 2020-12-17 14:45
This transformation of xml to html is handled [here](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/controllers/api.py#L54) in the ckanext-spatial extension. The methods appear to be unchanged when we moved from the [GSA fork ](https://github.com/GSA/ckanext-spatial/blob/master/ckanext/spatial/controllers/api.py) to upstream ckan but the html is not being returned correctly

**Comment by thejuliekramer** [comment] 2020-12-17 14:50
Also maybe worth noting this feature is included in the plugin `spatial_harvest_metadata_api` which we are including

**Comment by thejuliekramer** [comment] 2020-12-17 15:08
For testing locally I was using the harvest source `2016-kml-cd114-20` and dataset `/dataset/2015-cartographic-boundary-file-state-congressional-district-for-united-states-1-20000000`

**Comment by thejuliekramer** [comment] 2020-12-17 15:12
Also maybe worth noting that the dataset in question on old catalog when you load the url without the `/html` it is in [xml format ](https://catalog.data.gov/harvest/object/c9b20f57-0081-4930-aa19-0229052a61d4) while the same dataset in catalog-next without the `/html' is loading in [json format](https://catalog-next.data.gov/harvest/object/5a41bd01-096b-4115-8663-0e575d13d436)

**Comment by adborden** [comment] 2020-12-28 19:47
@thejuliekramer you're seeing a bug (missing feature) https://github.com/GSA/datagov-deploy/issues/2462. It should be XML in this case, but don't worry too much about that for this bug.

**Comment by thejuliekramer** [comment] 2021-01-05 20:32
Possible fix is to fix and push code upstream that was originally fixed in our old fork of ckanext-harvest here https://github.com/GSA/ckanext-harvest/commit/84ae3f9f8959eee31394367581653fb9aee26c8b#.

Closing as duplicate of #2462

**Closed** 2021-01-05 20:33 UTC
Labels: bug
