### ISSUE TITLE
[catalog-next]  Assess risk of SNYK-PYTHON-WEBOB-40490

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#408] opened 2020-08-28 16:30 UTC
No remediation path available for CKAN2.8 (not compatible with webob > 1.0.8).  Need to determine the risk of not upgrading.

## Acceptance Criteria
- Determine whether to remediate or accept risk
- Create new ticket for remediation if required

**Comment by thejuliekramer** [comment] 2021-01-11 19:11
Duplicate of https://github.com/GSA/catalog.data.gov/pull/169

**Closed** 2021-01-11 19:15 UTC
