### ISSUE TITLE
Datapusher fails to load data when submitted with resource_create

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/datagov-ckan-multi#488] opened 2020-10-16 18:03 UTC
When a file is uploaded using the new datapusher template, an error occurs and the file doesn't get uploaded. It looks like datapusher is trying to get the file from a URL instead of uploading the file. 

  - Sandbox Inventory-next 2.8
  - datapusher
  
- error log 
/var/log/inventory/datapusher.error.log

Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
   File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
     retval = job.func(*job.args, **job.kwargs)
   File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 354, in push_to_datastore
     'Only http, https, and ftp resources may be fetched.'
JobError: Only http, https, and ftp resources may be fetched.

## How to reproduce

1. Identify a dataset's package_id on inventory-next e.g. `f4d7e442-2990-4446-88dc-27089172b6b6`
1. Add a CSV resource to the dataset using the resource_create API. Here's an example:
```
curl -X POST https://inventory-next.sandbox.datagov.us/api/action/resource_create  \
  -F "package_id=f4d7e442-2990-4446-88dc-27089172b6b6" \
  -F "name=Test upload API" \
  -F "upload=@/Users/aarondborden/Downloads/datagovlserexus.csv" \
  -H "Authorization: $CKAN_API_KEY" | jq '.result.url'
```

## Expected behavior
The resource is created and the `url` field is set in the response data. Datapusher will automatically load the CSV data into Datastore.

## Actual behavior
Response status code is 200 but the `url` field is not set. Datapusher logs show data loading failed with: `JobError: Only http, https, and ftp resources may be fetched.`

**Comment by adborden** [comment] 2020-10-20 23:19
Assigning to @chris-macdermaid to confirmed the issue is specific to CKAN 2.8 and not the new metadata form.

@chris-macdermaid is this a blocker for inventory-next?

**Comment by adborden** [comment] 2020-10-24 00:33
Pairing with @chris-macdermaid on this. We've identified that there's something about how the form is submitting to resource_create that the resource is not getting a `url` set correctly, which should be set by the s3filestore extension.

Some other notes:
- The form currently has a work-around for https://github.com/GSA/datagov-deploy/issues/1177 which needs to be removed for CKAN 2.8.
- It looks like s3filestore is supposed to upload the file and then set the url.

**Comment by adborden** [comment] 2020-10-24 01:34
This looks to be the reproduction. It's not really related to the metadata form at all, only that resource_create is not setting a `url`. https://github.com/ckan/ckan/issues/3869 looks very familiar and I suspect that s3filestore needs to be updated for flask/CKAN 2.8 although I'm not seeing an existing bug in that repo.

```
curl -X POST https://inventory-next.sandbox.datagov.us/api/action/resource_create  \
  -F "package_id=f4d7e442-2990-4446-88dc-27089172b6b6" \
  -F "name=Test upload API" \
  -F "upload=@/Users/aarondborden/Downloads/datagovlserexus.csv" \
  -H "Authorization: $CKAN_API_KEY" | jq '.result.url'
```

I'm trying to test this in local development since s3filestore is not installed/configured. If the resource_create works, that pretty much narrows it down to ckanext-s3filestore.

**Comment by jbrown-xentity** [comment] 2020-11-09 19:52
We found that there is a new file upload type called `FlaskFileStorage` starting in CKAN2.7. This was not being handled properly in [our fork of the s3 extension](https://github.com/GSA/ckanext-s3filestore/blob/master/ckanext/s3filestore/plugin.py) (upstream version [here](https://github.com/okfn/ckanext-s3filestore/blob/master/ckanext/s3filestore/uploader.py)), which was causing new data uploads to fail. If the file isn't downloaded and stored properly, datapusher cannot function.
To fix this, we 
- added the [ALLOWED_UPLOAD_TYPES](https://github.com/okfn/ckanext-s3filestore/blob/master/ckanext/s3filestore/uploader.py#L9-L19) (the ckantoolkit is not available, hardcoded to the ckan2.7+ type)
- added the [get_underlying_file function](https://github.com/okfn/ckanext-s3filestore/blob/master/ckanext/s3filestore/uploader.py#L29-L32)
- updated the uploader functionality according to [upstream](https://github.com/okfn/ckanext-s3filestore/blob/master/ckanext/s3filestore/uploader.py#L247-L259).

This worked, live example [here](https://inventory-next.sandbox.datagov.us/dataset/james-test-3/resource/7566e970-beb6-4f92-a2b6-26f17ddc2293)

**Comment by jbrown-xentity** [comment] 2020-11-13 21:36
[This PR](https://github.com/GSA/inventory-app/pull/155) has the changes needed to implement s3 locally and includes the necessary changes.
The following still needs to be done:

- Figure out [circleci failure](https://app.circleci.com/pipelines/github/GSA/inventory-app/469/workflows/0d1c5edf-7c6b-4830-abed-f07f6c13b805/jobs/599) and fix
- Remove s3 installation in [ansible code](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/tasks/additional-tasks.yml#L2-L7) for inventory-next (may be other locations)
- Create branch of simplified changes and make upstream PR

**Comment by jbrown-xentity** [comment] 2020-11-13 23:01
Found that the test fails because localstack is failing to run properly. If you ssh onto circleci and run `docker-compose up localstack-container` and in another shell run `make test`, then tests pass.
Still not sure what the fix is, every time we run localstack manually the service has no problems...

**Comment by jbrown-xentity** [comment] 2020-11-16 22:46
Tests are failing again. When the resource gets created as part of the dataset, the dataset [automatically is made public](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L691-L698)... Ugh.
I believe this is related to https://github.com/GSA/datagov-deploy/issues/2314, and why some datasets are marked as public and some are not, although further research is needed.
Not sure what the best resolution in the short term is to get past the breaking test; I am considering removing the test completely as we no longer know what the intended functionality is.
@adborden @pjsharpe07 thoughts?

**Closed** 2020-12-23 18:04 UTC
Labels: bug
