### ISSUE TITLE
Harvesting Deployment into CKAN Cloud

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#129] opened 2019-08-26 15:21 UTC
We want to deploy the harvesting as part of the multi-tenant / CKAN Cloud.

## Acceptance criteria

* [ ] Harvesting system deployed as part of CKAN Cloud deploy with config in code (helm etc)
* [ ] Admin interface is available

## Tasks

* [ ] Helm chart for this setup
  * [ ] Airflow
  * [ ] Runners for harvesting
* [ ] Tests
* [ ] Documentation

**Comment by kimwdavidson** [comment] 2019-09-09 15:25
Duplicate of UAT provisioning ticket

**Closed by kimwdavidson** 2019-09-09 15:25 UTC
