### ISSUE TITLE
Incorporate Harvester NG into CKAN Cloud

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#140] opened 2019-09-09 15:34 UTC
As an operator, I want the new harvest platform to be deployed with the existing platform as infrastructure as code so that I changes to the harvest platform are made through our GitHub workflow and can easily be inspected for auditing and compliance.

## Acceptance criteria
- [ ] Docker image(s) created for Harvester and Airflow in "production" configuration
- [ ] Helm templates are created/updated to pull in the Harvester Docker image(s)
- [ ] Harvester instance in Sandbox using helm

**Comment by adborden** [comment] 2019-10-07 15:35
Duplicate of https://github.com/GSA/datagov-ckan-multi/issues/137

**Closed by adborden** 2019-10-07 15:35 UTC
